### ISSUE TITLE
Break out puppet modules into their own repos

### ISSUE THREAD

**Issue by brektyme** [jetstack/tarmak#1]
It would be nice if the puppet modules were broken out into their own repos. It makes contributing easier, makes tracking changes to the puppet modules easier, and allows for the modules to have their own versions.

**Comment by kragniz** [comment]
Hi @brektyme, we're going to be splitting these out soon as part of the process of moving tarmak into the open (we're going to be moving CI and issues from our internal gitlab instance onto github). Stay tuned!

**Comment by simonswine** [comment]
This has been done, see repos in jetstack org:

https://github.com/jetstack?q=puppet-module-
