### ISSUE TITLE
Add Tunnel resource to Tarmak Terraform provider

### ISSUE THREAD

**Issue by dippynark** [jetstack/tarmak#102]
Tarmak creates SSH tunnels for connecting to various environment components. This code should be pulled out into the Tarmak Terraform provider

**Comment by dippynark** [comment]
This can be done using https://github.com/stefansundin/terraform-provider-ssh
This creates an SSH tunnel as a data resource so that the tunnel is torn down when terraform stops

**Comment by dippynark** [comment]
The options that require an SSH tunnel are:
- Initialising Vault
- Creating/ensuring vault backends exist
- Ensure bastion is online
- Ensure wing is running on the bastion

These need to migrated to use `terraform-provider-ssh`

**Comment by simonswine** [comment]
The proposal for the tarmak provider suggests, that we don't tunnel from the terraform container to the bastion we rather stick to the current [proposal](https://docs.tarmak.io/proposals/terraform-provider.html) where tunneling is handled, as well as the heavy lifting by tarmak
