### ISSUE TITLE
Use a tarmak provider to merge all stacks into single

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#112]
/kind feature

This proposal suggests how to approach the implementation of a Terraform provider for Tarmak, to make Tarmak <-> Terraform interactions within a Terraform run more straightforward.

**Background**:

Right now the Terraform code for the AWS provider (the only one implemented) consists of multiple separate stacks (state, network, tools, vault, kubernetes). The Main reason for having these stacks is to enable Tarmak to do operations in between parts of the resource spin up. Examples for such operations are (list might not be complete):

    Bastion node needs to be up for other instances to check into Wing.
    Vault needs to be up and initialised, before PKI resources are created.
    Vault needs to contain a cluster’s PKI resources, before Kubernetes instances can be created (init-tokens).

The separation of stacks comes with some overhead for preparing Terraform apply (pull state, lock stack, plan run, apply run). Terraform can’t make use of parallel creation of resources that are independent from each other.

**Objective**:

An integration of these stacks into a single stack could lead to a substantial reduction of execution time.

As Terraform is running in a container is quite isolated from the Tarmak process:

    Requires some Terraform refactoring
    Should be done before implementing multiple providers

**Steps toward full integration**

- Phase A Merge state, network, tools and vault stack
  - [ ] Implement RPC unix socket server in tarmak #109 (to test it standalone)
  - [ ] Terraform provider supports the bastion_instance data resource #110 
  - [ ] Use a `docker exec` for communication stdin/stdout between tarmak <-> tarmak-connector and terraform-provider-tarmak
  - [ ] Rewrite terraform to contain state, network, tools and vault and use the bastion data resource a dependency for vault instances
 
- Phase B Merge kubernetes with the the other stacks

**Comment by dippynark** [comment]
UPDATE: The merged stacks now work in multi-cluster and existing VPC environments. The latest changes are in my namespace (https://github.com/dippynark/tarmak/tree/merge-terraform-stacks). There is an open PR for this (https://github.com/jetstack/tarmak/pull/148). The steps required before this can be merged include:
- Fix 'Unexpected RPC error' when changing the `FragmentSize` in `vendor/github.com/alecthomas/multiplex/multiplex.go` back to 1024

**Comment by simonswine** [comment]
@dippynark thanks for your effort.

Update from me: 
* I have removed the idea of stacks.  
* Vendored terraform and the required providers

Still a lot TODOs. But it's definitely end of day/brain for me :laughing: 

Great if you could take a look tomorrow @dippynark

**Comment by dippynark** [comment]
@simonswine nice, currently getting:
```
$ tarmak clusters apply                                                                                                    (home/default)
FATA[0000] unable to initialize tarmak: error initializing environment 'luke': 1 error occurred:

* refactore me!
```
so I'll work from there

**Comment by dippynark** [comment]
@simonswine returning nil above instead I am now getting:
```
$ tarmak clusters apply                                                                                                    (home/default)
INFO[0005] running apply                                 app=tarmak cluster=cluster environment=luke
DEBU[0005] created temporary directory: /var/folders/3k/xg9qp_d150l9kpp42_1yf0900000gn/T/tarmak-assets721844931
FATA[0005] Tarmak exited with an error.                  error="failed to move development snapshot of tarmak-container from /var/folders/3k/xg9qp_d150l9kpp42_1yf0900000gn/T/tarmak-assets721844931/tarmak-container_linux_amd64 to /var/folders/3k/xg9qp_d150l9kpp42_1yf0900000gn/T/tarmak-assets721844931/terraform/tarmak-container_linux_amd64: rename /var/folders/3k/xg9qp_d150l9kpp42_1yf0900000gn/T/tarmak-assets721844931/tarmak-container_linux_amd64 /var/folders/3k/xg9qp_d150l9kpp42_1yf0900000gn/T/tarmak-assets721844931/terraform/tarmak-container_linux_amd64: no such file or directory"
```
I can't see what has changed there as the only mention of `tarmak-container_linux_amd64` in the whole codebase is where that error is thrown. 

What's the purpose of the change in relation to this issue?
