### ISSUE TITLE
Provide a way to build a development tarmak, which by passes prod checks

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#117]
Goals

- [x] Build tarmak on Mac/Linux using Makefiles so that all latest components are used from this repo
  - [ ] Wing: currently hardcoded
  - [x] Terraform-Provider-Awstag: currently hardcoded

**Comment by charlieegan3** [comment]
At the moment, the version of the wing that is downloaded to nodes is hard coded at 0.3.0, the current release of the tarmak project.

https://github.com/jetstack/tarmak/blob/master/terraform/amazon/modules/kubernetes/templates/puppet_agent_user_data.yaml#L20

It is then installed using jetstack [Airworthy](https://github.com/jetstack/airworthy).
https://github.com/jetstack/tarmak/blob/master/terraform/amazon/modules/kubernetes/templates/puppet_agent_user_data.yaml#L31

This makes it hard to test out a development version of wing.

We have a few options to make this possible. All involve getting the wing binary in tarmak using go-bindata.

**'Low Effort' option**: tarmak hashes the wing binary and uploads it to a public-write s3 bucket at a path something like: `/wing_agent_binaries/HASH/wing`. Then this hash becomes the wing version and is passed down to the puppet config to be applied to each node and is used to fetch the correct version of the binary when booting the node.

**Terraform option**: Have terraform create a bucket for wing binaries that can be accessed from the nodes in the cluster. Perhaps upload it using a [Terraform bucket object](https://www.terraform.io/docs/providers/aws/r/s3_bucket_object.html) to a similar path based on the hash of the binary being uploaded. The hash is then similarly passed down as a wing env var to the puppet config and applied to the nodes.
