### ISSUE TITLE
Seg fault running tarmak clusters list with invalid config directory

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/tarmak#158]
/kind bug

**What happened**:
I ran `tarmak clusters list -c ~/.tarmak/tarmak.yaml`

And I get a seg fault:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0xe98c96]
...
```

**What you expected to happen**:
To see a list of clusters in that config file. 

I'd expect the following commands to return the same thing:
```
tarmak clusters list -c ~/.tarmak/tarmak.yaml
tarmak clusters list -c ~/.tarmak/
```

Or the first should print an error message if we don't want people doing that for some reason.

**How to reproduce it (as minimally and precisely as possible)**:
I have checked with Luke, he get's the same thing. My local tarmak binary is built from 3e4f5ae

**Comment by JoshVanL** [comment]
@charlieegan3 This sees to be fixed for me. Should this be closed?

**Comment by charlieegan3** [comment]
yeah - I can't replicate this any more either.

/close
