### ISSUE TITLE
Etcd encryption at rest

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#222]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We should support encryption at rest for our etcd nodes

**Anything else we need to know?**:

https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

We should consider encrypt secrets and configmaps per default in tarmak. The secrets should be generated as part of vault-helper and then deployed to the masters. A roll-over mechanism should not be part of this PR

**Comment by charlieegan3** [comment]
This was implemented in https://github.com/jetstack/tarmak/pull/292
