### ISSUE TITLE
Investigate why cluster list is slow

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#223]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Running cluster list on a larger tarmak.yaml is quite slow. I am suspecting we are doing a lot of validation calls. We should only list the clusters and not call anything external (like AWS libraries)

**Comment by simonswine** [comment]
I think to reproduce that you should have ten  `providers /> environments /> cluster` combinations and then the list gets quite slow. Let me know if you can't reproduce that. (That bug was created ages ago, things might have changed since then)

**Comment by alljames** [comment]
Unable to reproduce, likely as quite a bit of improvement has been done to the `pkg/tarmak/provider` code since this issue was opened. This issue can be closed.
/unassign
/assign @simonswine

**Comment by simonswine** [comment]
Thank you for your investigation, we can always reopen this ticket, if it comes up again
