### ISSUE TITLE
Generate API object reference documentation

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#239]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We need to document our configuration objects in a better and higher automated way. W

**What you expected to happen**:

We should use the same tooling as Kubernetes upstream.

Kube builder provides a good doc for it: 

http://book.kubebuilder.io/beyond_basics/generating_documentation.html

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- Install tools:
- Others:

**Comment by munnerz** [comment]
I've put together this PR to do the same for cert-manager: https://github.com/jetstack/cert-manager/pull/644

Could easily be reworked to work for Tarmak too. By blocker now is working out how to deploy/host the site (as well as linking to it)
