### ISSUE TITLE
Naming an environment with a hyphen causes subsequent failures to find the environment

### ISSUE THREAD

**Issue by leopoldodonnell** [jetstack/tarmak#3]
From `tarmak version: 0.1.2-rc3 builddate: 2017-10-10T01:23:37Z commit: 8ffcb8ceb518df0606af96cc79e4dc398db4449f`

Use a completely clean tarmak setup (ie first time user).

```bash
$ tarmak init
...
Enter a unique name for this environment [a-z0-9-]+
> tarmak-one
What is the project name? (default 'tarmak-playground')
> 
...
Continue with this cluster? [Y/n] Y
INFO[0081] successfully initialized cluster 'tarmak-one-cluster'
```
Now attempt to list the environment (or do anything else with it)

```bash
$ tarmak environments list
FATA[0000] unable to initialize tarmak: error finding environment 'tarmak' 
```

**Comment by munnerz** [comment]
I guess this is because the identifier for a cluster is stored as `${environment}-${cluster}` and we are probably splitting on `-` without specifically splitting on the *last* `-`

**Comment by simonswine** [comment]
As the environment and cluster name results in DNS labels down in the stack, we should probably make sure we don't allow hyphens there as well, as this `-` is the separator left.

@leopoldodonnell would you see a big need for `-` in environment / cluster names?

**Comment by leopoldodonnell** [comment]
It would be valuable to be more explicit about naming conventions in the docs. The existing validation for environments includes hyphens.

**Short Answer:**
I'd prefer that we could use some kind of separator, but at a minimum the decision should be enforced by validation.  Thanks!

**Long answer:**
It's not a deal-breaker to disallow hyphens, but naming does then become somewhat boxed in when you use an internal mulit-term naming convention; something like {division-prefix}-{product-group}.
Furthermore, ops folks can be further served on instance and cluster names that include some sort of indicator; we usually add the region into our naming. Sure this can be dealt with in many others ways, but anything that will help someone rolling out of bed at 3am is a positive.

**Comment by leopoldodonnell** [comment]
I'd just like to get a response before closing this

**Comment by simonswine** [comment]
https://github.com/jetstack/tarmak/commit/e2af904fa08a131d23ab56fcfd2864cfd7838523 implements proper validation and #7 is the follow up issue

**Comment by leopoldodonnell** [comment]
Thanks Christian!
