### ISSUE TITLE
Kubelet needs to set-up certificates with nodenames

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#33]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:

We are currently setting pretty generic kubelet CNs:

```
openssl x509 -in /etc/kubernetes/ssl/kubelet.pem -text | grep Subject:
        Subject: O=system:nodes, CN=system:node
```

**What you expected to happen**:

They should be set to:

```
        Subject: O=system:nodes, CN=system:node:ip-10-99-53-237.eu-west-1.compute.internal 
```

@JoshVanL can you please look into a fix. The line that needs changing is in:

https://github.com/jetstack/tarmak/blob/master/puppet/modules/tarmak/manifests/worker.pp#L23

Can you make sure that you can build a cluster successfully with 1.7 and provide a PR

**Comment by hiscal2015** [comment]
looks like I'm facing this issue, I'm using the same kubeconfig for all nodes, with Subject: O=system:nodes, CN=system:node in Kubernetes 1.11, now I have issue 
```
kubelet[1635]: E0914 21:00:57.033096    1635 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: nodes "10.10.100.10" is forbidden: User "system:node" cannot list nodes at the cluster scope
```
Is this a mandatory requirement in Kubernetes 1.11? What can I do if I want to use the same kubeconfig for all nodes?
