### ISSUE TITLE
Improve Tarmak env bootstrap process

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/tarmak#354]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
- Created a new multi-cluster env with `tarmak init`
- (built the images)
- Applied the hub, didn't have the vault_root_token created
- Applied the cluster, found that only then was the vault root token created
- Committed the id_rsa and vault_root_token to my tarmak config repo

**What you expected to happen**:
I expected the vault_root_token to be created when applying the hub as I thought it would be created when first initializing the vault cluster.

Doing this (first creating) the hub and then actually applying isn't really compatible with our tarmak-config / jenkins approach to rolling out clusters as it required running the first apply in a new environment locally first.

It would be great to have a feature like `tarmak cluster prepare|pregenerate` or have the vault_root_token written at the time of applying the hub cluster as a start.

Either way - I we ought to have a bit of a think about how initializing many new environments repeatable way.

**Comment by JoshVanL** [comment]
@charlieegan3 

This should be eventually fixed by https://github.com/jetstack/tarmak/pull/235 which fixes this https://github.com/jetstack/tarmak/issues/168.

Since the new vault-helper has been realised I'm no longer blocked and should be able to finish this PR which should fix this issue.

**Comment by charlieegan3** [comment]
Ahh good. Glad we've already got something going against this.
