### ISSUE TITLE
Customize vault-helper download URL

### ISSUE THREAD

**Issue by Wiston999** [jetstack/tarmak#393]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What you expected to happen**:
It would be useful to allow the override of the `vault-helper` download url in vault_client module so it can be downloaded from local mirrors instead of github.com

**Comment by JoshVanL** [comment]
@simonswine You've moved the open PR to this to 0.6 #619 
Guess we should move this to 0.6 too?
/assign @simonswine 
/unassign

**Comment by simonswine** [comment]
Yes good point we should
