### ISSUE TITLE
Implement Docker and journald log rotation

### ISSUE THREAD

**Issue by dippynark** [jetstack/tarmak#394]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: Docker and journald do not seem to be configured for log rotation, this should be fixed

**Comment by simonswine** [comment]
Can you provider more evidence there?

This is what has done the job for docker previously:
https://github.com/jetstack/tarmak/blob/master/puppet/modules/site_module/templates/docker.erb#L4
https://github.com/jetstack/tarmak/blob/master/puppet/modules/site_module/templates/docker.erb#L37

Not too sure if something changed when centos upgraded to docker 1.13

**Comment by dippynark** [comment]
Ah yeah, missed the OPTIONS, but I still think journald rotation needs configuring - it's using the defaults from `/etc/systemd/journald.conf` from what I can see which only limits the number of files rather than their total size

**Comment by simonswine** [comment]
To be ones not too sure, that might be well the case. Do we know which folder had the issues?

**Comment by dippynark** [comment]
@simonswine  from https://www.freedesktop.org/software/systemd/man/journald.conf.html, usage is capped at 4G - journald is currently storing everything in memory so long running nodes will tend towards 4G of memory used just for logs which is unrelated to this issue but may also be a problem
