### ISSUE TITLE
Provide instructions how to run ark in docs

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#430]

**Comment by zee-ahmed** [comment]
Ark was throwing an error whilst trying to create a backup.

`An error occurred: invalid configuration: no configuration has been provided ark`

This is down to the way Tarmak's documentation mentions how to reference the kube config as an environment variable. 

`export KUBECONFIG=$(tarmak cluster kubeconfig)`

The above command will generate the path to Tarmak but with duplication i.e 
`KUBECONFIG=KUBECONFIG=/home/zee/.tarmak/playground-cluster/kubeconfig` 

Ark will not be able to find a cluster profile based on this. The workaround is to manually export the kube config path for Tarmak to get Ark to create a backup, set a schedule etc or execute `export $(tarmak cluster kubeconfig)`

Result
`export KUBECONFIG=/home/zee/.tarmak/playground-cluster/kubeconfig`

```
ark backup describe nginx-backup                   
Name:         nginx-backup
Namespace:    heptio-ark
Labels:       ark.heptio.com/storage-location=default
Annotations:  <none>

Phase:  Completed
```

**Comment by alljames** [comment]
Thank you, @zee-ahmed ! Really valuable feedback. I've fixed the issue that you raised and pushed to the `arkdocexample` branch on `alljames/tarmak` for your reconsideration
/unassign
