### ISSUE TITLE
Data volume doesn't mount correctly with NVMe drives 

### ISSUE THREAD

**Issue by MattiasGees** [jetstack/tarmak#449]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The extra data EBS volume drive isn't mapped correct to the devicemapper of Docker. This only happens on NVMe instances (C5d or M5d).
It uses the NVMe drive instead.

```
Filesystem Size Used Avail Use% Mounted on
/dev/nvme0n1p1 100G 11G 90G 11% /
...
overlay 100G 11G 90G 11% 
/var/lib/docker/overlay2/c0e310f522c92f55551841e1df6e209dd9cb0a14c9b70f31a0647cdccd6d27e8/merged
overlay 100G 11G 90G 11% /var/lib/docker/overlay2/4ea68503df8e17e5545ef98de154215095c05ce9dde80588407288ddc4c46e1a/merged
...
/dev/nvme2n1 296G 4.1G 277G 2% /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/eu-west-2b/vol-xxxxxxxxxxx
```

**What you expected to happen**:
Docker uses EBS volume and not the NVMe drive,

**How to reproduce it (as minimally and precisely as possible)**:
Bring up a cluster with worker instances of C5d.large and start some pods. 

**Anything else we need to know?**:
This is possibly also happening on other types where we use custom volumes.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- Install tools:
- Others:

**Comment by simonswine** [comment]
We fixed the docker volume bits for instances with nvme volumes. We still need to address etcd/vault instances and their EBS moutning

**Comment by JoshVanL** [comment]
@simonswine I'll create a PR on top of #93 to re-use the puppet logic
