### ISSUE TITLE
Use of instance storage for Docker storage

### ISSUE THREAD

**Issue by MattiasGees** [jetstack/tarmak#457]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
Tarmak only supports EBS storage for Docker storage for the workers

**What you expected to happen**:
I think we should be able to let Docker use the instance storage as well when that is available. Instance storage is by nature faster (IOPS and latency). This would be good for the workers instance pool.

**How to reproduce it (as minimally and precisely as possible)**:
Bring up a cluster with instances for workers that support instance storage (eg C5d.large)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- Install tools:
- Others:

**Comment by simonswine** [comment]
Since #461 has been merged this should work by removing the default volume statement for docker volumes. Docker's puppet module will pick up the instance storage instead.

This needs to be tested and documented

**Comment by MattiasGees** [comment]
Tested this with `c5d.xlarge` and it works. Docker used the instance storage volume.
