### ISSUE TITLE
Enable EBS volume encryption

### ISSUE THREAD

**Issue by MattiasGees** [jetstack/tarmak#459]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:

In `terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template`
we create ebs volumes but we don't have a way of enabling encryption.

This is configured in terraform like this:
https://www.terraform.io/docs/providers/aws/r/ebs_volume.html#encrypted

This would likely be an extra instance pool attribute to enable encryption.

(written by Charlie)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- Install tools:
- Others:

**Comment by simonswine** [comment]
Ok I have been looking into this quite a bit and from my understanding we should do (This hack is enabling encryption everywhere and actually works https://github.com/jetstack/tarmak/compare/master...simonswine:add-ebs-kms-hack):

- [ ] Have a tarmak.yaml flag for enabling encryption (Default is disabled)
- [ ] Packer builds should support
- [ ] Discovery of AMI id should support a check if the actual AMI is acutally encrypted or not
- [ ] We need to make sure we don't destroy state in the vault/etcd EBS volumes 
- [ ] All the changes of the hack need to be templated into our terraform code

I don't think it would be feasible to support custom KMS keys, as the launch configuration doesn't support that for attached EBS volumes.

**Comment by simonswine** [comment]
/unassign @JoshVanL 
/assign @alljames 

@JoshVanL I would like aled to work on that feature. Maybe you can give him a bit of an intro where to look at and how to achieve that templating

**Comment by JoshVanL** [comment]
@simonswine Yep sure thing :+1:
