### ISSUE TITLE
Grafana dashboard port-forward not working

### ISSUE THREAD

**Issue by dippynark** [jetstack/tarmak#472]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: Running `tarmak kubectl port-forward $(tarmak kubectl get pods -l k8s-app=grafana -o jsonpath={.items..metadata.name}) 3000` or `tarmak kubectl port-forward service/monitoring-grafana 3000:80` gives 
<img width="481" alt="screen shot 2018-08-29 at 10 44 56" src="https://user-images.githubusercontent.com/28210877/44779899-993ae880-ab78-11e8-84e2-54c8dcfb89c0.png">

**What you expected to happen**: To see the Grafana dashboard

**How to reproduce it (as minimally and precisely as possible)**: Spin up a tarmak cluster and run the above commands

**Comment by MattiasGees** [comment]
@dippynark this should be fixed with https://github.com/jetstack/tarmak/pull/460
Also you have to access it through the proxy. I added some extra docs with that PR.
