### ISSUE TITLE
Metrics-server and heapster should use API proxy to connect to the node port

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#499]
/kind feature

**What happened**:

Both heapster and metrics-server use a direct connection to the kubelet to collect metrics. This is not a secure solution as it will allow everyone in the cluster to connect to the kubelet ports. We should do a similar approach like prometheus where we use the node proxy in the kubernetes api:

`https://kubernetes.default.svc:443/api/v1/nodes/<nodename>/proxy/metrics/cadvisor`

**What you expected to happen**:

We would need to provide the ability in the upstream node proxy to connect via the api endpoints (and should not forget the RBAC permission for it

**Comment by dippynark** [comment]
@simonswine are you saying this would involve a change to upstream metrics-server and heapster? 

I think we can just:
- Make Heapster/metrics-server use secure kubelet port 10250
- Make Heapster/metrics-server use service account bearer token
- Enable token auth on the kubelet: --authentication-token-webhook=true

Heapster/metrics-server wouldn't go through the api server but the connections would be encrypted and mutually authenticated and we could disable the read-only kubelet port

**Comment by dippynark** [comment]
I don't know if it's possible to prevent everyone from connecting to the kubelet ports, 10250 needs to be open for log collection/execing/port-forward AFAIK - but the above would at least force it to require credentials/RBAC permissions

**Comment by simonswine** [comment]
This is still a valid problem. Metrics server can't scrape the masters' kubelets because of that

**Comment by simonswine** [comment]
Again to solve this, we would need to make sure all connections to 10250 are authenticated.

We currently allow unauthenticated clients to connect to this 10250 ports to gather the metrics for metrics server.  The only way I would see that work, is if we use the kubernetes API server node proxy as source for the merics server. This requires an upstream feature/change in metrics-apiserver.

Opening port 10250 is something I would rather not do as it widens the attack surface on the control plane nodes and we rather want to be more restrictive of network access than opening it wider

**Comment by simonswine** [comment]
I have created a hot fix release here: https://github.com/jetstack/metrics-server/releases/tag/v0.3.1-jetstack.1

/cc @MattiasGees @JoshVanL 

If that works alright we might use it till it is accepted/released upstream
