### ISSUE TITLE
Add unlock command

### ISSUE THREAD

**Issue by dippynark** [jetstack/tarmak#509]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**: It is possible to not release the Dynamo lock when tarmak crashes or is force stopped

**What you expected to happen**: We should add a `tarmak clusters unlock` command to release the lock manually. We should include a warning to describe the possible dangers of doing this

**Comment by JoshVanL** [comment]
/assign
Note that this is less likely now with #169 merged
