### ISSUE TITLE
Results of kube-hunter test

### ISSUE THREAD

**Issue by alljames** [jetstack/tarmak#534]
I listened to a podcast with Liz Rice recently https://kubernetespodcast.com/episode/019-kube-hunter-and-kubecon/, who was talking about a new vulnerability scanner from AquaSec (https://github.com/aquasecurity/kube-hunter) inspired by the Tesla hack that occurred via their Kubernetes dashboards earlier in the year. Yesterday I ran three different tests against a clean Tarmak single cluster environment and Tarmak seems to have performed well - thought it was worth sharing the findings here.

*Test 1*

> `docker run --rm aquasec/kube-hunter --cidr {CLUSTERPUBLICIP}/24`

AquaSec description of the test:
This gives an attackers-eye-view of your Kubernetes setup.

No vulnerabilities were found :sunglasses:

*Test 2*

> `kubectl create` a _kube-hunter_ Job inside a cluster

AquaSec description of the test:
This option lets you discover what running a malicious container can do/discover on your cluster.
This gives a perspective on what an attacker could do if they were able to compromise a pod, perhaps through a software vulnerability.

```
Vulnerabilities
+--------------------+----------------------+----------------------+----------------------+----------------------+
| LOCATION           | CATEGORY             | VULNERABILITY        | DESCRIPTION          | EVIDENCE             |
+--------------------+----------------------+----------------------+----------------------+----------------------+
| 10.99.58.185:10255 | Information          | K8s Version          | The kubernetes       | v1.10.6              |
|                    | Disclosure           | Disclosure           | version could be     |                      |
|                    |                      |                      | obtained from logs   |                      |
|                    |                      |                      | in the /metrics      |                      |
|                    |                      |                      | endpoint             |                      |
+--------------------+----------------------+----------------------+----------------------+----------------------+
| 10.99.58.185:10255 | Information          | Exposed Pods         | An attacker could    | count: 8             |
|                    | Disclosure           |                      | view sensitive       |                      |
|                    |                      |                      | information about    |                      |
|                    |                      |                      | pods that are bound  |                      |
|                    |                      |                      | to a Node using the  |                      |
|                    |                      |                      | /pods endpoint       |                      |
+--------------------+----------------------+----------------------+----------------------+----------------------+
| 10.99.58.185:10255 | Information          | Cluster Health       | By accessing the     | status: ok           |
|                    | Disclosure           | Disclosure           | open /healthz        |                      |
|                    |                      |                      | handler, an attacker |                      |
|                    |                      |                      | could get the        |                      |
|                    |                      |                      | cluster health state |                      |
|                    |                      |                      | without              |                      |
|                    |                      |                      | authenticating       |                      |
+--------------------+----------------------+----------------------+----------------------+----------------------+
| 10.99.58.185:10255 | Access Risk          | Privileged Container | A Privileged         | pod: calico-node-    |
|                    |                      |                      | container exist on a | bfdcg, container:    |
|                    |                      |                      | node. could expose   | calic...             |
|                    |                      |                      | the node/cluster to  |                      |
|                    |                      |                      | unwanted root        |                      |
|                    |                      |                      | operations           |                      |
+--------------------+----------------------+----------------------+----------------------+----------------------+
```

*Test 3*

> Run the _kube-hunter_ container from inside the Master node and have it scan all subnets.

I had to run _kube-hunter_ docker image as a privileged container, so I'd take this test's findings with a pinch of salt.
The following report was generated, which identifies some vulnerabilities, all of them low or medium risk:
https://kube-hunter.aquasec.com/report.html?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0aW1lIjoxNTM3Mjk1OTg5LjI0MTU2NiwiZW1haWwiOiJhbGVkam1zQGdtYWlsLmNvbSIsInIiOiI2NmU4MDE5MiJ9.u9e1hJlssFIUlNgIy2B-3EABRQoQL4t2MVzJG-L1q3o

So in conclusion, there are some low to medium risks *IF* an attacker gains access to the cluster, but they'd need to get unauthorised access to the cluster in the first place, and _kube-hunter_ couldn't identify a single such vulnerability / point of entry.

**Comment by simonswine** [comment]
If you don't mind it would be great to rerun the test on #639 

/assign @alljames

**Comment by simonswine** [comment]
Thanks for rerunning the tests, I think we should be fine. The privileged pod risk is a risk to take
