### ISSUE TITLE
Tarmak init for new multi cluster environments should set the hub as the current cluster

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/tarmak#556]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:

- I created a new environment and a multi-cluster within it.
- When I tried to apply the cluster I found that state bucket was missing.
- I set the current cluster as the hub
- Built the images
- Had to remove my local terraform directory for that cluster as it seems to have a reference to a non-existent terraform lock.
- I then hit https://github.com/jetstack/tarmak/issues/555
- Thankfully, re-running the cluster apply had given the time for some things to get created. This time it worked
- Finally I applied the non-hub cluster completing the process.

**What you expected to happen**:

I would have liked some of the following to happen:

- tarmak prompt me that in a multi cluster env, I need to apply the hub first to get the state bucket
- Tarmak to default to the hub cluster after initializing a new multicluster environment. Current it sets the current cluster to the non-hub cluster instead.

**Comment by alljames** [comment]
I was unable to reproduce the precise error that that led you to encounter #555 , but I agree that when `tarmak init` is run for the first time, the current cluster should be set to hub (I'm also seeing Tarmak default to the worker cluster by default), and that the user should be prompted to apply the hub first. Will look at changing this behaviour

**Comment by charlieegan3** [comment]
@alljames yeah, #555 is going to be a tough one to replicate reliably
