### ISSUE TITLE
Tarmak uses reserved instance offerings to validate sizes of on-demand instances

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/tarmak#642]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I tried to create a cluster with some `m5.large` instances in `eu-west-2c`. At the time of writing, `m5.large` instances were not available for reservation in that zone. However, it is still possible to create on-demand instances in the same zone (I created some instances manually)

**What you expected to happen**:
I expected the cluster to validate after seeing that I could create on-demand instances of this type.

**Environment**:
Tarmak version: 0.5

**Comment by charlieegan3** [comment]
Tarmak source: https://github.com/jetstack/tarmak/blob/df13157a2b0e81232d0f5ea39a9c5479f9eb24ab/pkg/tarmak/provider/amazon/amazon.go#L623

**Comment by MattiasGees** [comment]
In the longer term we can transition to https://docs.aws.amazon.com/sdk-for-go/api/service/pricing/ but atm it is only available in 2 regions.

Eg from CLI
```
aws pricing get-attribute-values --service-code AmazonEC2 --attribute-name instanceType --region us-east-1

{
    "AttributeValues": [
        {
            "Value": "a1.2xlarge"
        },
...
        {
            "Value": "z1d"
        }
    ]
}
```

**Comment by charlieegan3** [comment]
Tarmak is passing the `--offering-type 'No Upfront'` parameter, without this, more instance types are returned.

Is there a reason we need to specify an offering type? And must it be `No Upfront`?

cli command that approx matches the tarmak query

```
aws ec2 describe-reserved-instances-offerings --filters "Name=availability-zone,Values=eu-west-2c" --region eu-west-2 --instance-type m5.large --offering-class standard --product-description 'Linux/UNIX (Amazon VPC)' --offering-type 'No Upfront' --instance-tenancy default --no-include-marketplace | jq '.ReservedInstancesOfferings[] | .InstanceType'
```

**Comment by seanturner83** [comment]
This is a bit of a sod, it's happening at the moment in one of the us-east-1 AZs and stops you using the tooling effectively. I think a "--skip-instance-type-check" flag would help
