### ISSUE TITLE
Vault data disks not mounted

### ISSUE THREAD

**Issue by MattiasGees** [jetstack/tarmak#697]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:
Vault clusters don't mount and use their data EBS volume. The disk gets created in AWS but doesn't get mounted to the vault instance.

**What you expected to happen**:
2 disks mounted on every instance in the vault cluster.

**How to reproduce it (as minimally and precisely as possible)**:
`tarmak init`
`tarmak apply`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration**:
- Install tools:
- Others:

**Comment by simonswine** [comment]
Sounds like a regression of #93, can you investigate @JoshVanL. I was able to reproduce that, with an existing config

/assign @JoshVanL
