### ISSUE TITLE
EBS protection potentially broken

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#729]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

/kind bug

**What happened**:

You mentioned that EBS protection is potentially broken @JoshVanL 

**What you expected to happen**:

tbd

**How to reproduce it (as minimally and precisely as possible)**:

tbd

**Anything else we need to know?**:

tbd

**Comment by JoshVanL** [comment]
Query input is broken when running tarmak. It is unresponsive and always fails. 
This seems to occur only when terraform is running/has run
