### ISSUE TITLE
Issue with IAM permissions on master. 

### ISSUE THREAD

**Issue by BenCoughlan15** [jetstack/tarmak#748]
BUG REPORT

> Uncomment only one, leave it on its own line: 
>
kind bug
> /kind feature

**What happened**:
https://github.com/kubernetes/kops/issues/5816

**What you expected to happen**:
add 
`        "elasticloadbalancing:DeregisterTargets",`

to tarmak/terraform/amazon/modules/kubernetes/templates/iam_elb_controller.json

**How to reproduce it (as minimally and precisely as possible)**:
Try to use an elb with externalDNS, it doesn'trecreate, and floods the aws account with trash. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- Install tools:
- Others:

**Comment by JoshVanL** [comment]
/assign
Hi @BenCoughlan15, thanks for this.

We have created a PR for this here https://github.com/jetstack/tarmak/pull/750
as well as a PR for https://github.com/jetstack/tarmak/issues/479,  https://github.com/jetstack/tarmak/pull/749

We should be able to squeeze this into 0.6 which is coming out very soon! https://github.com/orgs/jetstack/projects/1

**Comment by BenCoughlan15** [comment]
Thanks Josh, We've rolled it into our local version for now. 

Cheers, 
Ben
