### ISSUE TITLE
tarmak does not refresh templated terraform properly

### ISSUE THREAD

**Issue by dippynark** [jetstack/tarmak#762]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: Created a destroyed a cluster using 0.5.3, created a tarmak cluster using 0.6.1, ran a plan (no changes), deleted local templated terraform folder, ran plan again and there were changes

**What you expected to happen**: terraform plan should template manifests from the current version only and not leave files lying around from pervious versions

**How to reproduce it (as minimally and precisely as possible)**: as above

**Comment by simonswine** [comment]
This was addresses as part of this PR #768
