### ISSUE TITLE
Update to use lowercase logrus import

### ISSUE THREAD

**Issue by munnerz** [jetstack/tarmak#99]
Currently it is not easy to build tarmak on a case insensitive file system (such as OSX) due to it still using the old `Sirupsen` import path for logrus.

The official advice from the logrus repo is the all projects should always use the lower-case variant:

```
Seeing weird case-sensitive problems? It's in the past been possible to import Logrus as both upper- and lower-case. Due to the Go package environment, this caused issues in the community and we needed a standard. Some environments experienced problems with the upper-case variant, so the lower-case was decided. Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.
```

In order to do this, we'll need to also bump the versions of some of our dependencies that were vendored whilst they still referenced the caps-variant of logrus.

All of our effected projects *have* been updated to use the lower-case variant, so we don't need to submit any upstream PRs. The following is a list of the dependencies that we need to update:

* `docker/docker` (renamed to moby/moby, but github redirect will save us rewriting all imports)
* `docker/go-connections`
* `opencontainers/runc`
* `jetstack/vault-unsealer` - https://github.com/jetstack/vault-unsealer/pull/11
* `jetstack/vault-helper` - https://github.com/jetstack/vault-helper/pull/4

Once the two PRs on the jetstack projects above are merged, I will be able to put a PR into tarmak so we can get a test run performed against these new versions of dependencies.

/cc @simonswine @dippynark

**Comment by simonswine** [comment]
Ok I have started and merged with vault-unsealer. Now I have some issues with building the pipeline, but I should be able to sort that soonish

**Comment by munnerz** [comment]
👍 let me know once you've tagged a new release of vault-unsealer & vault-helper and I can create a similar PR here

**Comment by simonswine** [comment]
Both should be tagged now, happy to take a look myself. I rather have the docker package renamed to be honest. Always causes confusion, as godoc for docker no longer works...
